name: ci

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
        
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

      - name: Run lint
        run: make lint

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Setup for unit test
        run: make test-up

      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Run unit test
        run: make test

      - name: Post run unit test
        if: ${{ always() }}
        run: make test-down
